import { Smartphone, FolderOpen, Info } from 'lucide-react';

export default function MobileProjectsPage() {
  return (
    <div className="page-body" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

      <div className="card" style={{ padding: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
        <Smartphone size={18} style={{ color: 'var(--accent-teal)', flexShrink: 0 }} />
        <div>
          <div style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--text-primary)' }}>Mobile App Projects</div>
          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.15rem' }}>
            Generated by the Website &amp; Mobile App pipeline
          </div>
        </div>
      </div>

      <div className="card" style={{ padding: '2rem', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem', textAlign: 'center' }}>
        <FolderOpen size={40} style={{ color: 'var(--accent-blue)', opacity: 0.6 }} />
        <div>
          <div style={{ fontSize: '0.95rem', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '0.4rem' }}>
            Mobile prompts are saved on NAS
          </div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', lineHeight: 1.6, maxWidth: 480 }}>
            The Website &amp; Mobile App pipeline saves generated Cursor prompts to:<br />
            <code style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', background: 'var(--bg-surface)', padding: '0.2rem 0.5rem', borderRadius: '4px', display: 'inline-block', marginTop: '0.5rem' }}>
              /n8n_data/Website &amp; Mobile App Generator/projects/&#123;username&#125;/mobile_*
            </code>
          </div>
        </div>
        <div style={{
          display: 'flex', alignItems: 'flex-start', gap: '0.5rem',
          background: 'rgba(13,148,136,0.08)', border: '1px solid rgba(13,148,136,0.2)',
          borderRadius: 'var(--radius-md)', padding: '0.75rem 1rem',
          fontSize: '0.78rem', color: 'var(--text-secondary)', maxWidth: 480, textAlign: 'left',
        }}>
          <Info size={13} style={{ color: 'var(--accent-teal)', flexShrink: 0, marginTop: '0.1rem' }} />
          <span>
            Open the generated <code style={{ fontFamily: 'var(--font-mono)' }}>mobile_*</code> folder in <strong>Cursor</strong> and run the numbered <code style={{ fontFamily: 'var(--font-mono)' }}>.md</code> prompt files in order to build your React Native + Expo app.
          </span>
        </div>
      </div>
    </div>
  );
}
