import { useState, useEffect } from 'react';
import { Smartphone, FolderOpen, MessageSquare, Clock, Trash2, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface ChatSession {
  id:        string;
  title:     string;
  createdAt: string;
  updatedAt: string;
  pipeline?: 'web' | 'webapp';
}

const SESSIONS_KEY = 'n8n-webapp-sessions-v1';

function timeAgo(ts: string) {
  const diff = Date.now() - new Date(ts).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function loadSessions(): ChatSession[] {
  try {
    const all: ChatSession[] = JSON.parse(localStorage.getItem(SESSIONS_KEY) || '[]');
    return all.filter(s => (s.pipeline ?? 'webapp') === 'webapp');
  } catch { return []; }
}

export default function MobileProjectsPage() {
  const navigate = useNavigate();
  const [sessions, setSessions] = useState<ChatSession[]>([]);

  useEffect(() => {
    setSessions(loadSessions());
  }, []);

  const deleteSession = (id: string) => {
    const updated = sessions.filter(s => s.id !== id);
    setSessions(updated);
    localStorage.setItem(SESSIONS_KEY, JSON.stringify(updated));
    localStorage.removeItem(`n8n-msgs-${id}`);
    localStorage.removeItem(`n8n-building-${id}`);
  };

  return (
    <div className="page-body" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>

      {/* Header card */}
      <div className="card" style={{ padding: '1.125rem 1.375rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <div style={{
            width: 36, height: 36, borderRadius: '9px',
            background: 'rgba(45,212,191,0.1)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
          }}>
            <Smartphone size={18} style={{ color: 'var(--accent-teal)' }} />
          </div>
          <div>
            <div style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)', letterSpacing: '-0.01em' }}>
              Mobile App Projects
            </div>
            <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginTop: '1px' }}>
              Generated by the Website &amp; Mobile App pipeline · {sessions.length} project{sessions.length !== 1 ? 's' : ''}
            </div>
          </div>
        </div>
        <button
          className="btn btn-primary btn-sm"
          onClick={() => navigate('/chat-webapp')}
          style={{ gap: '0.35rem' }}
        >
          <MessageSquare size={13} /> New Project
        </button>
      </div>

      {/* Project list */}
      {sessions.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {sessions.map(s => (
            <div
              key={s.id}
              className="card"
              style={{
                padding: '1rem 1.25rem',
                display: 'flex', alignItems: 'center', gap: '1rem',
                cursor: 'pointer',
                transition: 'border-color var(--transition)',
              }}
              onClick={() => navigate('/chat-webapp')}
            >
              {/* Icon */}
              <div style={{
                width: 38, height: 38, borderRadius: '9px', flexShrink: 0,
                background: 'rgba(96,165,250,0.1)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <FolderOpen size={17} style={{ color: 'var(--accent-blue)' }} />
              </div>

              {/* Title + meta */}
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{
                  fontSize: '0.875rem', fontWeight: 600,
                  color: 'var(--text-primary)', whiteSpace: 'nowrap',
                  overflow: 'hidden', textOverflow: 'ellipsis',
                }}>
                  {s.title || 'Untitled Project'}
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginTop: '0.2rem' }}>
                  <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                    <Clock size={10} /> Created {timeAgo(s.createdAt)}
                  </span>
                  {s.updatedAt !== s.createdAt && (
                    <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                      · Updated {timeAgo(s.updatedAt)}
                    </span>
                  )}
                  <span style={{
                    fontSize: '0.6rem', fontWeight: 700,
                    padding: '0.15rem 0.45rem', borderRadius: '999px',
                    background: 'rgba(45,212,191,0.1)',
                    border: '1px solid rgba(45,212,191,0.2)',
                    color: 'var(--accent-teal)',
                  }}>
                    Website + App
                  </span>
                </div>
              </div>

              {/* NAS path hint */}
              <div style={{
                fontSize: '0.68rem', color: 'var(--text-muted)',
                fontFamily: 'var(--font-mono)',
                display: 'flex', flexDirection: 'column', alignItems: 'flex-end',
                flexShrink: 0, gap: '0.1rem',
              }}>
                <span style={{ opacity: 0.6 }}>NAS →</span>
                <span>projects/…/mobile_*</span>
              </div>

              {/* Actions */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.375rem', flexShrink: 0 }}>
                <button
                  className="btn btn-ghost btn-sm btn-icon"
                  title="Open in chat"
                  onClick={e => { e.stopPropagation(); navigate('/chat-webapp'); }}
                >
                  <ArrowRight size={13} />
                </button>
                <button
                  className="btn btn-ghost btn-sm btn-icon"
                  title="Remove from list"
                  style={{ color: 'var(--accent-red)' }}
                  onClick={e => { e.stopPropagation(); deleteSession(s.id); }}
                >
                  <Trash2 size={13} />
                </button>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="card">
          <div className="empty-state" style={{ padding: '3rem' }}>
            <Smartphone size={36} className="empty-state-icon" />
            <div className="empty-state-title">No projects yet</div>
            <div className="empty-state-text" style={{ marginBottom: '1.25rem' }}>
              Start a new chat in <strong>Website &amp; Mobile App</strong> to generate your first project.
              Files will be saved to your NAS automatically.
            </div>
            <button
              className="btn btn-primary btn-sm"
              onClick={() => navigate('/chat-webapp')}
            >
              <MessageSquare size={13} /> Start a project
            </button>
          </div>
        </div>
      )}

      {/* NAS path info — only show as a footer note, not the whole page */}
      {sessions.length > 0 && (
        <div style={{
          display: 'flex', alignItems: 'center', gap: '0.5rem',
          padding: '0.625rem 0.875rem',
          background: 'rgba(45,212,191,0.05)',
          border: '1px solid rgba(45,212,191,0.15)',
          borderRadius: 'var(--radius-md)',
          fontSize: '0.72rem', color: 'var(--text-muted)',
        }}>
          <FolderOpen size={12} style={{ color: 'var(--accent-teal)', flexShrink: 0 }} />
          Files saved on NAS at
          <code style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)', fontSize: '0.7rem' }}>
            /n8n_data/Website &amp; Mobile App Generator/projects/&#123;username&#125;/
          </code>
          — open the <code style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem' }}>mobile_*</code> folder in Cursor.
        </div>
      )}
    </div>
  );
}
