const express = require('express');
const router = express.Router();
const AdmZip = require('adm-zip');
const path = require('path');

// POST /api/wordpress/convert
// Converts generated React/HTML content into a WordPress theme structure
router.post('/convert', (req, res) => {
  const { projectName, pages, globalContext, githubRepo } = req.body;
  const io = req.app.get('io');
  const updateState = req.app.get('updateState');

  if (!projectName || !pages || !Array.isArray(pages)) {
    return res.status(400).json({ error: 'projectName and pages[] are required' });
  }

  try {
    updateState({ pipeline: { wordpress: 'running' } });
    io.emit('pipeline:step', { step: 'wordpress', status: 'running' });

    const themeName = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const zip = new AdmZip();

    // Pages that are prompt/context files — NOT real WordPress pages
    const PROMPT_PAGE_IDS   = new Set(['00', '01']);
    const PROMPT_PAGE_NAMES = ['art_direction', 'environment_and_routing', 'supabase', 'schema'];
    const isPromptPage = (page) => {
      if (PROMPT_PAGE_IDS.has(String(page.id))) return true;
      const n = (page.name || '').toLowerCase();
      return PROMPT_PAGE_NAMES.some(kw => n.includes(kw));
    };

    // Only real feature pages become PHP templates
    const themePages = (pages || []).filter(p => !isPromptPage(p));

    // Theme URI: use passed repo, else env, else empty
    const repoUri = githubRepo
      ? `https://github.com/${githubRepo}`
      : (process.env.GITHUB_OWNER && process.env.GITHUB_REPO)
        ? `https://github.com/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}`
        : '';

    // ── style.css ──────────────────────────────────────────────────────────────
    const styleCss = `/*
Theme Name: ${projectName}
${repoUri ? `Theme URI: ${repoUri}` : ''}
Author: Generated by n8n Dashboard
Description: Auto-generated WordPress theme from n8n AI pipeline.
Version: 1.0.0
License: MIT
Text Domain: ${themeName}
*/

/* Generated from React/TypeScript via n8n Dashboard */
:root {
  --color-primary: ${globalContext?.color_palette?.split(',')[0]?.trim() || '#0a0e1a'};
  --color-text: ${globalContext?.color_palette?.split(',')[1]?.trim() || '#e8edf8'};
  --color-accent: ${globalContext?.color_palette?.split(',')[2]?.trim() || '#4f8fff'};
  --font-base: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: var(--font-base);
  background: var(--color-primary);
  color: var(--color-text);
  line-height: 1.6;
}

.container { max-width: 1200px; margin: 0 auto; padding: 0 1.5rem; }
a { color: var(--color-accent); text-decoration: none; }
a:hover { text-decoration: underline; }
img { max-width: 100%; height: auto; }
`;

    // ── functions.php ───────────────────────────────────────────────────────────
    const functionsPHP = `<?php
/**
 * ${projectName} Theme Functions
 * Generated by n8n Dashboard on ${new Date().toISOString()}
 */

if ( ! defined( 'ABSPATH' ) ) exit;

define( '${themeName.toUpperCase().replace(/-/g, '_')}_VERSION', '1.0.0' );

function ${themeName.replace(/-/g, '_')}_setup() {
    add_theme_support( 'title-tag' );
    add_theme_support( 'post-thumbnails' );
    add_theme_support( 'html5', ['search-form','comment-form','comment-list','gallery','caption'] );
    add_theme_support( 'custom-logo' );
    add_theme_support( 'responsive-embeds' );

    register_nav_menus([
        'primary' => __( 'Primary Menu', '${themeName}' ),
        'footer'  => __( 'Footer Menu',  '${themeName}' ),
    ]);
}
add_action( 'after_setup_theme', '${themeName.replace(/-/g, '_')}_setup' );

function ${themeName.replace(/-/g, '_')}_scripts() {
    wp_enqueue_style( '${themeName}-style', get_stylesheet_uri(), [], ${themeName.toUpperCase().replace(/-/g, '_')}_VERSION );
    wp_enqueue_script( '${themeName}-main', get_template_directory_uri() . '/assets/js/main.js', [], ${themeName.toUpperCase().replace(/-/g, '_')}_VERSION, true );
}
add_action( 'wp_enqueue_scripts', '${themeName.replace(/-/g, '_')}_scripts' );

function ${themeName.replace(/-/g, '_')}_widgets_init() {
    register_sidebar([
        'name'          => __( 'Main Sidebar', '${themeName}' ),
        'id'            => 'sidebar-1',
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget'  => '</section>',
        'before_title'  => '<h3 class="widget-title">',
        'after_title'   => '</h3>',
    ]);
}
add_action( 'widgets_init', '${themeName.replace(/-/g, '_')}_widgets_init' );
`;

    // ── header.php ──────────────────────────────────────────────────────────────
    const headerPHP = `<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo( 'charset' ); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<header class="site-header">
  <div class="container">
    <div class="site-branding">
      <?php the_custom_logo(); ?>
      <a href="<?php echo esc_url( home_url('/') ); ?>" class="site-title">
        <?php bloginfo('name'); ?>
      </a>
    </div>
    <nav class="primary-nav">
      <?php wp_nav_menu(['theme_location' => 'primary', 'menu_class' => 'nav-list']); ?>
    </nav>
  </div>
</header>
<main class="site-main">
`;

    // ── footer.php ──────────────────────────────────────────────────────────────
    const footerPHP = `</main>
<footer class="site-footer">
  <div class="container">
    <p>&copy; <?php echo date('Y'); ?> <?php bloginfo('name'); ?>. All rights reserved.</p>
    <?php wp_nav_menu(['theme_location' => 'footer', 'menu_class' => 'footer-nav']); ?>
  </div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
`;

    // ── index.php ───────────────────────────────────────────────────────────────
    const indexPHP = `<?php
/**
 * Main template file — ${projectName}
 */
get_header(); ?>

<div class="container">
  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article id="post-<?php the_ID(); ?>" <?php post_class('entry'); ?>>
      <h2 class="entry-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      <div class="entry-content"><?php the_excerpt(); ?></div>
    </article>
  <?php endwhile; else : ?>
    <p>No content found.</p>
  <?php endif; ?>
</div>

<?php get_footer();
`;

    // ── page.php ────────────────────────────────────────────────────────────────
    const pagePHP = `<?php
/**
 * Default page template — ${projectName}
 */
get_header(); ?>

<div class="container page-content">
  <?php while ( have_posts() ) : the_post(); ?>
    <h1 class="page-title"><?php the_title(); ?></h1>
    <div class="page-body"><?php the_content(); ?></div>
  <?php endwhile; ?>
</div>

<?php get_footer();
`;

    // ── single.php ──────────────────────────────────────────────────────────────
    const singlePHP = `<?php
/**
 * Single post template — ${projectName}
 */
get_header(); ?>

<div class="container single-content">
  <?php while ( have_posts() ) : the_post(); ?>
    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
      <h1 class="entry-title"><?php the_title(); ?></h1>
      <div class="entry-meta">
        <time datetime="<?php echo get_the_date('c'); ?>"><?php echo get_the_date(); ?></time>
        <?php the_author_posts_link(); ?>
      </div>
      <div class="entry-content"><?php the_content(); ?></div>
      <?php the_post_navigation(); ?>
    </article>
    <?php comments_template(); ?>
  <?php endwhile; ?>
</div>

<?php get_footer();
`;

    // ── archive.php ─────────────────────────────────────────────────────────────
    const archivePHP = `<?php
/**
 * Archive template — ${projectName}
 */
get_header(); ?>

<div class="container">
  <header class="archive-header">
    <h1 class="archive-title"><?php the_archive_title(); ?></h1>
    <?php the_archive_description('<div class="archive-description">', '</div>'); ?>
  </header>

  <div class="archive-grid">
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
      <article id="post-<?php the_ID(); ?>" <?php post_class('archive-item'); ?>>
        <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
        <div class="entry-excerpt"><?php the_excerpt(); ?></div>
      </article>
    <?php endwhile;
      the_posts_navigation();
    else : ?>
      <p><?php esc_html_e( 'No posts found.', '${themeName}' ); ?></p>
    <?php endif; ?>
  </div>
</div>

<?php get_footer();
`;

    // ── 404.php ─────────────────────────────────────────────────────────────────
    const notFoundPHP = `<?php
/**
 * 404 Not Found template — ${projectName}
 */
get_header(); ?>

<div class="container" style="text-align:center; padding: 6rem 1.5rem;">
  <h1 style="font-size: clamp(4rem, 15vw, 10rem); opacity: .15; margin: 0;">404</h1>
  <h2><?php esc_html_e( 'Page Not Found', '${themeName}' ); ?></h2>
  <p><?php esc_html_e( "The page you're looking for doesn't exist or has been moved.", '${themeName}' ); ?></p>
  <a href="<?php echo esc_url( home_url('/') ); ?>" class="btn-primary">
    <?php esc_html_e( 'Back to Home', '${themeName}' ); ?>
  </a>
</div>

<?php get_footer();
`;

    // ── search.php ──────────────────────────────────────────────────────────────
    const searchPHP = `<?php
/**
 * Search results template — ${projectName}
 */
get_header(); ?>

<div class="container">
  <header class="search-header">
    <h1><?php printf( esc_html__( 'Search Results for: %s', '${themeName}' ), '<span>' . get_search_query() . '</span>' ); ?></h1>
    <?php get_search_form(); ?>
  </header>

  <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <article id="post-<?php the_ID(); ?>" <?php post_class('search-result'); ?>>
      <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
      <div class="entry-excerpt"><?php the_excerpt(); ?></div>
    </article>
  <?php endwhile;
    the_posts_navigation();
  else : ?>
    <p><?php esc_html_e( 'No results found. Try a different search term.', '${themeName}' ); ?></p>
    <?php get_search_form(); ?>
  <?php endif; ?>
</div>

<?php get_footer();
`;

    // ── screenshot placeholder ───────────────────────────────────────────────────
    const screenshotNote = `Replace this file with a 1200x900 PNG named screenshot.png to show a theme preview in the WordPress admin.`;

    // ── Build ZIP ──────────────────────────────────────────────────────────────
    zip.addFile(`${themeName}/style.css`,       Buffer.from(styleCss));
    zip.addFile(`${themeName}/functions.php`,   Buffer.from(functionsPHP));
    zip.addFile(`${themeName}/header.php`,      Buffer.from(headerPHP));
    zip.addFile(`${themeName}/footer.php`,      Buffer.from(footerPHP));
    zip.addFile(`${themeName}/index.php`,       Buffer.from(indexPHP));
    zip.addFile(`${themeName}/page.php`,        Buffer.from(pagePHP));
    zip.addFile(`${themeName}/single.php`,      Buffer.from(singlePHP));
    zip.addFile(`${themeName}/archive.php`,     Buffer.from(archivePHP));
    zip.addFile(`${themeName}/404.php`,         Buffer.from(notFoundPHP));
    zip.addFile(`${themeName}/search.php`,      Buffer.from(searchPHP));
    zip.addFile(`${themeName}/screenshot-note.txt`, Buffer.from(screenshotNote));
    zip.addFile(`${themeName}/assets/js/main.js`,   Buffer.from(`// Main JS — ${projectName}\ndocument.addEventListener('DOMContentLoaded', function() {\n  // IntersectionObserver scroll reveal\n  const els = document.querySelectorAll('[data-reveal]');\n  const io = new IntersectionObserver(entries => entries.forEach(e => {\n    if (e.isIntersecting) { e.target.classList.add('revealed'); io.unobserve(e.target); }\n  }), { threshold: 0.1 });\n  els.forEach(el => io.observe(el));\n});\n`));

    // Add real feature pages as WordPress page templates (skip prompt/context pages)
    themePages.forEach((page) => {
      const slug = (page.name || 'page').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
      const templateContent = `<?php
/**
 * Template Name: ${page.name}
 */
get_header(); ?>

<div class="container page-content" data-wp-section="${slug}">
  <h1 class="page-title"><?php the_title(); ?></h1>
  <?php the_content(); ?>
</div>

<?php get_footer(); ?>
`;
      zip.addFile(`${themeName}/page-${slug}.php`, Buffer.from(templateContent));
    });

    const zipBuffer = zip.toBuffer();

    updateState({ pipeline: { wordpress: 'done' } });
    io.emit('pipeline:step', { step: 'wordpress', status: 'done' });

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${themeName}-wp-theme.zip"`);
    res.send(zipBuffer);

  } catch (err) {
    updateState({ pipeline: { wordpress: 'error' } });
    io.emit('pipeline:step', { step: 'wordpress', status: 'error', error: err.message });
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
